language: java
env: 
  - ENV=PRODUCTION
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 45fcbf6e-6c03-4a61-a9a0-fd2c0fb0d948
  